---
Author: Gábor Bettesch
Version: 155 17-CNL 113 439, Rev. C
Date: 2012-10-12

---
= IUA Protocol Modules for TTCN-3 Toolset with TITAN, Function Specification
:author: Gábor Bettesch
:revnumber: 155 17-CNL 113 439, Rev. C
:revdate: 2012-10-12
:toc:

== How to Read This Document

This is the Function Specification for the set of IUA protocol modules. IUA protocol modules are developed for the TTCN-3 Toolset with TITAN.

== Scope

The purpose of this document is to specify the content of the IUA protocol modules.

= General

Protocol modules implement the message structures of the related protocol in a formalized way, using the standard specification language TTCN-3. This allows defining of test data (templates) in the TTCN-3 language <<_2, [2]>> and correctly encoding/decoding messages when executing test suites using the Titan TTCN-3 test environment.

Protocol modules are using Titan’s RAW encoding attributes <<_3, [3]>> and hence are usable with the Titan test toolset only.

= Functional Specification

== Protocol Version Implemented

This set of protocol modules implements protocol messages and constants of a draft IUA protocol (see <<_1, [1]>>).

[[modifications-deviations-related-to-the-protocol-specification]]
== Modifications/deviations Related to the Protocol Specification

=== Implemented Messages

All IUA message types of message classes 0, 3, 4 and 5 as listed in chapter 3.1.2 of <<_1, [1]>> will be implemented.

Parameters with the following identifiers will be implemented (see chapter 3.1.5 of <<_1, [1]>>): 0x0001, 0x0003, 0x0004, 0x0005, 0x0007, 0x0008, 0x0009, 0x000b, 0x000c, 0x000d, 0x000e, 0x000f, 0x0010, and 0x0011.

[[protocol-modifications-deviations]]
=== Protocol Modifications/Deviations

Although the interface identifier parameters 0x0001, 0x0008 (integer) and 0x0003 (text) are mutually exclusive (see e.g. chapter 3.3.2.5 in <<_1, [1]>>), this restriction has not been implemented.

[[encoding-decoding-and-other-related-functions]]
== Encoding/Decoding and Other Related Functions

This product also contains encoding/decoding functions that assure correct encoding of messages when sent from Titan and correct decoding of messages when received by Titan. Implemented encoding/decoding functions. Via using the backtrack decoder function dynamic testcase error can be avoided when trying to decode invalid message (in this case the return value won’t be `_0_`):

[cols=3*,options=header]
|===

|Name
|Type of formal parameters
|Type of return value

|`enc_PDU_IUA`
|PDU_IUA
|octetstring

|`dec_PDU_IUA`
|octetstring
|PDU_IUA

|`dec_PDU_IUA_backtrack`
|octetstring, PDU_IUA
|integer
|===

== Limitations

Debug log generation is not supported when this revision of this product is used with TITAN version R7A (1.7pl0), because the encoder/decoder functions, automatically generated by TITAN version R7A (1.7pl0) does not contain logging functions. Newer versions of TITAN supports the debug logging within the automatically generated encoder/decoder functions that can be activated by allowing the `DEBUG_ENCDEC` (see <<_3, [3]>>, clause 7.2.3.2) in TITAN runtime configuration files.

= Terminology

TITAN TTCN-3 Test Executor (see <<_3, [3]>>).

= Abbreviations

ISDN:: Integrated Services Digital Network

IUA:: ISDN User Application Layer Protocol

PDU:: Protocol Data Unit

TTCN-3:: Testing and Test Control Notation version 3

= References

[[_1]]
[1] https://tools.ietf.org/html/draft-ietf-sigtran-rfc3057bis-02[draft-ietf-sigtran-rfc3057bis-02.txt] +
ISDN Q.921-User Adaptation Layer

[[_2]]
[2] ETSI ES 201 873-1 v.4.4.1 (2012) +
The Testing and Test Control Notation version 3. Part 1: Core Language

[[_3]]
[3] User Documentation for the TITAN TTCN-3 Test Executor
