/******************************************************************************
* Copyright (c) 2005, 2015  Ericsson AB
* All rights reserved. This program and the accompanying materials
* are made available under the terms of the Eclipse Public License v1.0
* which accompanies this distribution, and is available at
* http://www.eclipse.org/legal/epl-v10.html
*
* Contributors:
* Laszlo Farkas
* Attila Balasko
* Gabor Bettesch
* Gabor Szalai
* Istvan Sandor
******************************************************************************/
//
//  File:		IUA_EncDec.cc
//  Rev:		R5A
//  Prodnr:             CNL 113 439
///////////////////////////////////////////////////////////////////////////////

// Please note: Because the encoder/decoder functions are generated by the 
// TITAN, the IUA_EncDec.cc is kept only for compatibility issue and 
// should be removed from the projects.
